@echo off
chcp 65001 >nul
title 启动 Gemma4 vLLM + ONYX
cd /d "%~dp0"
echo [1] 检查权重…
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0scripts\install-gemma-weights.ps1" 2>nul
echo [2] 启动 vLLM（新窗口，加载约需数分钟）…
start "vLLM Gemma4" cmd /k "%~dp0scripts\START_VLLM_GEMMA4.bat"
echo [3] 等待健康检查…
timeout /t 30 /nobreak >nul
echo [4] 启动 ONYX（本机模型）…
call START_APP_LOCAL.bat
