"""#12–#38 变现与自动化专家席（共 27）。按关键词路由，不默认全员连聊。"""

from __future__ import annotations

from typing import Any

# no 12–38, id, name, keywords, focus（一句话职责）
MONETIZE_27: list[dict[str, Any]] = [
    {
        "id": "revenue_architect",
        "no": 12,
        "name": "变现架构师·ROI",
        "focus": "商业模式、收入公式、单元经济、30/90天现金流路径",
        "keywords": ["赚钱", "变现", "roi", "收入", "商业模式", "现金流", "毛利"],
    },
    {
        "id": "workflow_automation",
        "no": 13,
        "name": "工作流自动化·RPA",
        "focus": "n8n/Zapier/脚本/定时任务，把人手步骤改成无人值守",
        "keywords": ["自动化", "rpa", "工作流", "n8n", "zapier", "cron", "定时"],
    },
    {
        "id": "ecommerce_ops",
        "no": 14,
        "name": "电商运营·转化",
        "focus": "店铺转化、详情页、购物车、复购与客单价",
        "keywords": ["电商", "淘宝", "京东", "拼多多", "shopify", "转化", "sku"],
    },
    {
        "id": "content_pipeline",
        "no": 15,
        "name": "内容流水线·爆款",
        "focus": "选题→脚本→多平台分发→数据复盘的一键流水线",
        "keywords": ["内容", "爆款", "脚本", "短视频", "小红书", "公众号", "分发"],
    },
    {
        "id": "seo_growth",
        "no": 16,
        "name": "SEO/GEO增长·自然流",
        "focus": "搜索词、落地页、外链与结构化数据，拿免费流量",
        "keywords": ["seo", "geo", "搜索", "关键词", "排名", "自然流量", "sem"],
    },
    {
        "id": "paid_ads",
        "no": 17,
        "name": "付费投放·ROAS",
        "focus": "巨量/腾讯/谷歌投放结构、素材、出价与回本周期",
        "keywords": ["投放", "广告", "roas", "cpc", "巨量", "千川", "google ads"],
    },
    {
        "id": "social_matrix",
        "no": 18,
        "name": "社媒矩阵·日更",
        "focus": "多账号排期、互动话术、热点借势与粉丝转化",
        "keywords": ["社媒", "矩阵", "日更", "抖音", "b站", "ins", "twitter", "养号"],
    },
    {
        "id": "email_crm",
        "no": 19,
        "name": "邮件私域·复购",
        "focus": "邮件序列、标签分层、唤醒沉默用户与复购活动",
        "keywords": ["邮件", "edm", "私域", "crm", "复购", "newsletter"],
    },
    {
        "id": "affiliate_lead",
        "no": 20,
        "name": "联盟带货·佣金",
        "focus": "选品、佣金对比、挂链与转化追踪",
        "keywords": ["联盟", "带货", "佣金", "cps", "分销", "淘宝客", "affiliate"],
    },
    {
        "id": "data_leads",
        "no": 21,
        "name": "商业线索·采集",
        "focus": "公开渠道线索清洗、去重、打分与导入 CRM（合规前提）",
        "keywords": ["线索", "lead", "采集", "爬虫", "商机", "拓客", "crm导入"],
    },
    {
        "id": "pricing_offer",
        "no": 22,
        "name": "定价促销·毛利",
        "focus": "定价带、套餐设计、满减/捆绑与毛利测算",
        "keywords": ["定价", "促销", "折扣", "套餐", "毛利", "客单价"],
    },
    {
        "id": "funnel_copy",
        "no": 23,
        "name": "漏斗文案·成交",
        "focus": "落地页、详情页、私信话术与成交闭环文案",
        "keywords": ["文案", "落地页", "成交", "转化文案", "销售页", "话术"],
    },
    {
        "id": "customer_success",
        "no": 24,
        "name": "客服自动化·留存",
        "focus": "FAQ 机器人、工单分流、满意度与续费挽回",
        "keywords": ["客服", "售后", "留存", "续费", "工单", "faq"],
    },
    {
        "id": "contract_b2b",
        "no": 25,
        "name": "B2B商机·投标",
        "focus": "招标信息筛选、方案骨架、报价与跟进节奏",
        "keywords": ["b2b", "招标", "投标", "方案", "企业客户", "saas销售"],
    },
    {
        "id": "local_business",
        "no": 26,
        "name": "本地生活·到店",
        "focus": "团购、点评、到店核销与同城引流",
        "keywords": ["本地", "团购", "美团", "大众点评", "到店", "同城"],
    },
    {
        "id": "saas_product",
        "no": 27,
        "name": "SaaS产品化·MRR",
        "focus": "功能切片、订阅定价、试用转化与月经常性收入",
        "keywords": ["saas", "订阅", "mrr", "试用", "付费墙", "会员"],
    },
    {
        "id": "api_integration",
        "no": 28,
        "name": "API集成·零人力",
        "focus": "多系统 API 对接、Webhook、对账与异常告警",
        "keywords": ["api", "webhook", "集成", "对接", "openapi", "自动化对接"],
    },
    {
        "id": "report_finance",
        "no": 29,
        "name": "财务看板·现金流",
        "focus": "收支分类、利润表、应收应付与周报复盘",
        "keywords": ["财务", "报表", "现金流", "利润", "对账", "excel"],
    },
    {
        "id": "compliance_money",
        "no": 30,
        "name": "变现合规·风控",
        "focus": "广告法、平台规则、税务与合同红线（先合规再放大）",
        "keywords": ["合规", "风控", "税务", "合同", "广告法", "平台规则"],
    },
    {
        "id": "ab_experiment",
        "no": 31,
        "name": "AB实验·迭代",
        "focus": "假设—实验—指标—决策，小步快跑放大赢家",
        "keywords": ["ab测试", "实验", "指标", "迭代", "hypothesis", "转化提升"],
    },
    {
        "id": "inventory_supply",
        "no": 32,
        "name": "供应链·库存",
        "focus": "补货节奏、安全库存、滞销处理与成本优化",
        "keywords": ["供应链", "库存", "补货", "仓储", "物流", "进销存"],
    },
    {
        "id": "creator_monetize",
        "no": 33,
        "name": "创作者变现·分成",
        "focus": "平台激励、商单报价、粉丝经济与多元收入",
        "keywords": ["创作者", "up主", "商单", "mcn", "打赏", "分成"],
    },
    {
        "id": "course_info",
        "no": 34,
        "name": "知识付费·课程",
        "focus": "课程大纲、发售节奏、社群交付与退款控制",
        "keywords": ["知识付费", "课程", "训练营", "专栏", "发售"],
    },
    {
        "id": "live_commerce",
        "no": 35,
        "name": "直播带货·脚本",
        "focus": "直播节奏、话术、憋单与复盘数据",
        "keywords": ["直播", "带货", "直播间", "憋单", "场控"],
    },
    {
        "id": "cross_border",
        "no": 36,
        "name": "跨境出海·多币种",
        "focus": "选品、物流、关税与多站点运营",
        "keywords": ["跨境", "出海", "amazon", "tiktok shop", "独立站", "外贸"],
    },
    {
        "id": "agent_product",
        "no": 37,
        "name": "Agent产品化·交付",
        "focus": "把自动化能力打包成可售服务/订阅与交付清单",
        "keywords": ["agent", "智能体", "打包", "交付", "外包", "代运营"],
    },
    {
        "id": "passive_income_audit",
        "no": 38,
        "name": "被动收入审计·盘点",
        "focus": "盘点现有资产（内容/代码/数据）如何持续进账",
        "keywords": ["被动收入", "睡后", "资产", "盘点", "复利", "躺赚"],
    },
]

MONETIZE_IDS: tuple[str, ...] = tuple(x["id"] for x in MONETIZE_27)
